### ISSUE TITLE
debian-builder does not build source packages anymore

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/debian-builder#4]
It seems the problem is due to debian buster no longer being the stable release. It's hard (for me) to see where exactly the issue emerges in sbuild. The sources.list in /etc/apt/ should become:
```
deb http://deb.debian.org/debian buster main contrib non-free
deb-src http://deb.debian.org/debian buster main contrib non-free

deb http://deb.debian.org/debian buster-updates main contrib non-free
deb-src http://deb.debian.org/debian buster-updates main contrib non-free

deb http://deb.debian.org/debian buster-backports main contrib non-free
deb-src http://deb.debian.org/debian buster-backports main contrib non-free

deb http://security.debian.org/debian-security/ buster/updates main contrib non-free
deb-src http://security.debian.org/debian-security/ buster/updates main contrib non-free
```

But other fixes may be necessary that I cannot discover in this repo.

**Comment by gdrosos** [comment]
Thank you very much for both the catch and the fix! I believe it is better practise to copy the sources.list in the docker image instead of updating to Debian 11 bullseye. I have added the copy procedure to all the remaining dockerfiles where the build of the docker image failed because of this issue. Should we encounter another problem caused by the no longer stable buster release, we should reopen this issue.
