### ISSUE TITLE
Cscout output messages can contain wrong sourcePath 

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/debian-builder#6]
The Debian-builder/Cscout output messages can contain wrong sourcePath fields in cases where multiple output packages are generated. This happens for instance for the following coordinate:

`libgda5:libgda5:5.2.8-1|{"package": "libgda5", "version": "5.2.8-1", "arch": "amd64", "release": "buster", "source": "libgda5", "source_version": "5.2.8-1", "date": ""}`

(Pipe that coordinate to a local docker-compose setup to observe the problem, like here: https://github.com/fasten-project/fasten-docker-deployment#feeding-the-pipeline)

The output messages of Cscout then look like:
```
{
   "plugin_name": "CScoutKafkaPlugin",
   "plugin_version": "0.0.1",
   "input": {
      "package": "libgda5",
      "version": "5.2.8-1",
      "arch": "amd64",
      "release": "buster",
      "source": "libgda5",
      "source_version": "5.2.8-1",
      "date": ""
   },
   "created_at": "1650306786.781111",
   "payload": {
      "dir": "/mnt/fasten/revision-callgraphs/debian/callgraphs/l/libgda-5.0-dev/buster/5.2.8-1/amd64/file.json",
      "forge": "debian",
      "product": "libgda-5.0-dev",
      "version": "5.2.8-1",
      "arch": "amd64",
      "dist": "buster",
      "sourcePath": "/mnt/fasten/revision-callgraphs/debian/sources/l/libgda-5.0-dev/5.2.8-1"
   }
}
```
The problem is that the `sourcePath` field here is incorrect, it says `/mnt/fasten/revision-callgraphs/debian/sources/l/libgda-dev/5.2.8-1` but on disk there is `/mnt/fasten/revision-callgraphs/debian/sources/l/libgda5/5.2.8-1`, without the `-dev`. For the other output packages it is similar, it seems the `sourcePath` field is generated using the output package_name.

There are in fact 5 output packages generated by cscout for this coordinate, `libgda-5.0-4` `libgda-bin` `libgda-dev` `libgda-mysql` and `libgda-postgres`. Their messages all have the same problem.

This is an issue for downstream plugins (such as quality-analyzer and I suppose the debian-license-feeder) because they cannot find the source code in these cases.

I think the fix is to have the debian-builder construct the `sourcePath` based on where it actually got the source, not the resulting package names.

Also tagging @michelescarlato here fyi.

**Comment by michelescarlato** [comment]
Hi All, I raised a similar point [#414](https://github.com/fasten-project/fasten/issues/414).

What is clear from the above output message is that `product` seems to contain the correct value (and not `package` or `source` as I was trying to guess in #414).

The Debian license detector is getting license information from the Debian APIs (parsing the provided JSONs, file by file), so it is not an issue the `sourcePath` in this case (while it would be in the case of Python, because the python detector scans the code contained in the `sourcePath`).

Anyway, in the Debian APIs there is no info for the sub-packages: `libgda-5.0-4` , `libgda-5.0-bin`, `libgda-5.0-dev`, `libgda-5.0-mysql` and `libgda-5.0-postgres`, because as far as I am observing, these are compiled by the OS, and all of them are included in this sub-directory of the libgda5 package:
[https://sources.debian.org/src/libgda5/5.2.8-1/debian/](https://sources.debian.org/src/libgda5/5.2.8-1/debian/)

I guess that `Cscout/Debian builder` is building/compiling the code in this case.
Currently, the detector will run as many times as the MetadataDBCExtension.out is produced, upon the source and version recursively retrieved from input that is dragging in its Kafka message ([here](https://github.com/fasten-project/fasten/blob/develop/analyzer/debian-license-detector/src/main/java/eu/fasten/analyzer/debianlicensedetector/DebianLicenseDetectorPlugin.java#L246-L289) is the code that the detector uses).

If we can live with that (running the license detection multiple times, with theoretically the same result), I would need to investigate a behavior that I will try to explain in detail in [#442](https://github.com/fasten-project/fasten/issues/442), as soon as I better understand its nature (the license feeder seems to be consuming 7 times a Kafka message, produced by the license detector, containing info regarding dhcpd5 instead of the one regarding libgda5).

**Comment by MagielBruntink** [comment]
Please, let's stay on topic here and focus here on the bug that causes `sourcePath` to be wrong in some cases. This is a problem for other plugins.

**Comment by gdrosos** [comment]
Thanks @MagielBruntink  for discovering this issue and for the detailed report!
Indeed the Debian-Builder/Cscout  produces output messages with wrong sourcePath for binary packages which do not have the same name with the source package.
With the 77a005a I tried to address the issue by inserting into the sourcePath field the actual path of the source package.
Furthermore, after succesfullyng testing this fix with docker-compose, I will redeloy the plugin (and consequently the whole C pipeline) on monster.

**Comment by MagielBruntink** [comment]
I ran tests locally and I can confirm that this is resolved. Great work @gdrosos !
